# Generated by Django 5.2.17 on 2026-09-03 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='platform',
            field=models.CharField(default='Gmail', max_length=50),
        ),
        migrations.AlterField(
            model_name='topic',
            name='similarity_threshold',
            field=models.FloatField(default=0.35),
        ),
        migrations.CreateModel(
            name='UserMailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('Gmail', 'Gmail'), ('Outlook', 'Outlook / Hotmail / Office365'), ('Yahoo', 'Yahoo Mail'), ('iCloud', 'Apple iCloud'), ('Custom', 'Custom IMAP')], default='Gmail', max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('imap_server', models.CharField(default='imap.gmail.com', max_length=150)),
                ('imap_port', models.IntegerField(default=993)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
