# Generated by Django 5.2.17 on 2026-09-03 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_usermailbox_password_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmatch',
            name='cross_encoder_score',
        ),
    ]
