# Generated by Django 5.2.17 on 2026-09-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_remove_emailmatch_cross_encoder_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lm_studio_api_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lm_studio_model',
            field=models.CharField(blank=True, default='qwen/qwen3-1.7b', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lm_studio_url',
            field=models.CharField(blank=True, default='http://127.0.0.1:1234/v1', max_length=255),
        ),
    ]
