# Generated by Django 5.2.17 on 2026-09-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_userprofile_lm_studio_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='similarity_threshold',
            field=models.FloatField(default=0.45),
        ),
    ]
