# Generated by Django 5.2.17 on 2026-09-09 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_topic_similarity_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermailbox',
            name='provider_access_token',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='usermailbox',
            name='provider_refresh_token',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='usermailbox',
            name='provider_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermailbox',
            name='provider_type',
            field=models.CharField(choices=[('imap', 'IMAP (Polling/Idle)'), ('gmail', 'Gmail API Watch'), ('outlook', 'Microsoft Graph Webhook')], default='imap', max_length=20),
        ),
        migrations.AddField(
            model_name='usermailbox',
            name='trigger_mode',
            field=models.CharField(choices=[('polling', 'Polling'), ('webhook', 'Webhook'), ('auto', 'Auto (Best Available)')], default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='usermailbox',
            name='webhook_compare_with_polling',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usermailbox',
            name='webhook_cursor',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='usermailbox',
            name='webhook_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermailbox',
            name='webhook_event_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usermailbox',
            name='webhook_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermailbox',
            name='webhook_last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='usermailbox',
            name='webhook_last_event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermailbox',
            name='webhook_resource_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usermailbox',
            name='webhook_secret_token',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='usermailbox',
            name='webhook_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('pending', 'Pending'), ('active', 'Active'), ('error', 'Error')], default='disabled', max_length=20),
        ),
        migrations.AddField(
            model_name='usermailbox',
            name='webhook_subscription_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usermailbox',
            name='webhook_validation_token',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook'), ('imap', 'IMAP'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('event_type', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('received', 'Received'), ('rejected', 'Rejected'), ('queued', 'Queued'), ('processed', 'Processed'), ('error', 'Error')], default='received', max_length=20)),
                ('detail', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('mailbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='application.usermailbox')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
